config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("ftb.users.urls", namespace="users")),
    path("", include("ftb.core.urls", namespace="core"),),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ftb/core/urls.py
from django.urls import path, include
from django.conf.urls import url

from ftb.core import views

app_name = "core"
urlpatterns = [
    path("", views.home, name="home"),
    path("federacao/", views.federacao, name="federacao"),
    path("noticias/", views.noticias, name="noticias"),
    path("noticias/<int:noticia_id>/", views.noticia_detalhes, name="noticia_detalhes"),
    path("eventos/", views.eventos, name="eventos"),
    path("eventos/<int:evento_id>/", views.evento_detalhes, name="evento_detalhes"),
    path("eventos/<int:evento_id>/inscricao", views.iframe, name="iframe"),
    path("contato/", views.contato, name="contato"),
    path("estatuto/", views.estatuto, name="estatuto"),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

ftb/users/urls.py
from django.urls import path

from ftb.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

ftb/core/models.py
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver

from model_utils import Choices
from ckeditor.fields import RichTextField


class AbstractModel(models.Model):
    titulo = models.CharField('Título', max_length=100)
    descricao = RichTextField('Descrição', blank=True, null=True)
    criado_em = models.DateTimeField('Criado em', auto_now_add=True)
    atualizado_em = models.DateTimeField('Atualizado em', auto_now=True)

    class Meta:
        abstract = True


class Noticia(AbstractModel):
    imagem = models.ImageField(upload_to='notiticas/imagens', verbose_name='Imagem',
                               null=True, blank=True)
    ordem = models.IntegerField('Ordem', null=True, blank=True)
    destaque = models.BooleanField('Em destaque?', default=False)

    def __str__(self):
        return '{}'.format(self.titulo)

    class Meta:
        verbose_name = 'Notícia'
        verbose_name_plural = 'Notícias'


class Evento(AbstractModel):
    TIPO_EVENTO_COMPETICAO = 10
    TIPO_EVENTO_CURSO = 20

    tipo_evento_choices = Choices(
        (TIPO_EVENTO_COMPETICAO, 'Competição'),
        (TIPO_EVENTO_CURSO, 'Curso')
    )

    tipo_evento = models.IntegerField('Tipo', choices=tipo_evento_choices)
    imagem = models.ImageField(upload_to='eventos/imagens', verbose_name='Imagem',
                               null=True, blank=True)
    data_inicio = models.DateField('Início')
    data_fim = models.DateField('Fim')
    inscricao_data_inicio = models.DateField('Início das inscrições')
    inscricao_data_fim = models.DateField('Fim das inscrições')
    inscricao_formulario = models.CharField('Formulário', max_length=1000)
    # pdf = models.FileField(upload_to='eventos/pdfs', verbose_name='Regulamento/Normas')


@receiver(post_delete, sender=Evento)
@receiver(post_delete, sender=Noticia)
def submission_delete(sender, instance, **kwargs):
    instance.imagem.delete(False)
    # if sender.__name__ == "Evento":
    #     instance.pdf.delete(False)

ftb/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

ftb/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

ftb/core/views.py
from django.shortcuts import render
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail

from .models import Noticia, Evento


def home(request):
    noticias_recentes = Noticia.objects.all().order_by('-criado_em')[:2]
    noticias_destaque = Noticia.objects.filter(destaque=True).order_by('criado_em')[:3]
    template_name = "core/home.html"
    context = {
        'noticias_recentes': noticias_recentes,
        'noticias_destaque': noticias_destaque
    }
    return render(request, template_name, context)


def federacao(request):
    template_name = "core/federacao.html"
    context = {}
    return render(request, template_name, context)


def noticias(request):
    noticias = Noticia.objects.all().order_by('-criado_em')
    template_name = "core/noticias.html"
    context = {
        'noticias': noticias
    }
    return render(request, template_name, context)


def noticia_detalhes(request, noticia_id):
    noticia = Noticia.objects.get(pk=noticia_id)
    template_name = "core/artigo.html"
    context = {
        'artigo': noticia
    }
    return render(request, template_name, context)


def eventos(request):
    cursos = Evento.objects.filter(tipo_evento=Evento.TIPO_EVENTO_CURSO)
    competicoes = Evento.objects.filter(tipo_evento=Evento.TIPO_EVENTO_COMPETICAO)
    template_name = "core/eventos.html"
    context = {
        'cursos': cursos,
        'competicoes': competicoes
    }
    return render(request, template_name, context)


def evento_detalhes(request, evento_id):
    evento = Evento.objects.get(pk=evento_id)
    template_name = "core/artigo.html"
    context = {
        'artigo': evento
    }
    return render(request, template_name, context)


def contato(request):
    data = request.POST
    nome = None
    email = None
    mensagem = None

    if request.method == 'POST':
        nome = data['nome']
        email = data['email']
        mensagem = data['mensagem']

        subject = '[CONTATO-SITE] - Usuário: %s, Email: %s' % (nome, email)
        message = mensagem
        from_email = settings.EMAIL_HOST_USER
        to_list = [settings.EMAIL_HOST_USER]

        send_mail(subject, message, from_email, to_list, fail_silently=True)

        messages.success(request, 'Seu email foi recebido,  em breve entraremos em contato!')

    template_name = "core/contato.html"
    context = {}
    return render(request, template_name, context)


def estatuto(request):
    template_name = "core/estatuto.html"
    context = {}
    return render(request, template_name, context)


def iframe(request, evento_id):
    evento = Evento.objects.get(pk=evento_id)
    template_name = "core/inscricao.html"
    context = {
        'evento': evento
    }
    return render(request, template_name, context)

ftb/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

ftb/templates/403_csrf.html
{% extends "base_old.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

ftb/templates/base.html
<!DOCTYPE html>
{% load static i18n %}
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <title>Basquete Tocantins</title>
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic">
  <link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'fonts/ionicons.min.css' %}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora">
  <link rel="stylesheet" href="{% static 'css/Article-Clean.css' %}">
  <link rel="stylesheet" href="{% static 'css/Article-Dual-Column.css' %}">
  <link rel="stylesheet" href="{% static 'css/Contact-Form-Clean.css' %}">
  <link rel="stylesheet" href="{% static 'css/Footer-Dark.css' %}">
  <link rel="stylesheet" href="{% static 'css/Projects-Horizontal.css' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/Swipe-Slider-9.css' %}">
  <link rel="stylesheet" href="{% static 'css/Team-Clean.css' %}">
</head>

<body>
<div class="row no-gutters">
  <div class="col-5 col-sm-4 col-md-2 col-lg-2 col-xl-2 text-center text-sm-center text-md-center text-lg-center text-xl-center align-self-center">
    <img class="nav-logo" src="{% static 'img/Logo-FTB.png' %}">
  </div>
  <div class="col-8 d-none d-sm-none d-md-inline d-lg-inline d-xl-inline align-self-center">
    <h2 class="nav-title">Federação Tocantinense de Basquete</h2>
  </div>
  <div class="col-6 col-sm-7 col-md-2 col-lg-2 col-xl-2 text-right text-sm-right text-md-center text-lg-center text-xl-center align-self-center item social">
    <a href="https://www.facebook.com/basquetetocantins/" target="_blank">
      <i class="icon ion-social-facebook"></i>
    </a>
    <a href="https://instagram.com/basquetetocantins?igshid=1bvehyuftyj57" target="_blank">
      <i class="icon ion-social-instagram"></i>
    </a>
  </div>
</div>
<div class="row no-gutters">
  <div class="col">
    <nav class="navbar navbar-light navbar-expand-md navbar-ftb">
      <div class="container-fluid"><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navcol-1">
          <ul class="nav navbar-nav">
            <li class="nav-item" role="presentation"><a class="nav-link {% if request.resolver_match.url_name == "home" %}active{% endif %}" href="{% url 'core:home' %}">Inicio</a></li>
            <li class="nav-item" role="presentation"><a class="nav-link {% if request.resolver_match.url_name == "federacao" %}active{% endif %}" href="{% url 'core:federacao' %}">A Federação</a></li>
            <li class="nav-item" role="presentation"><a class="nav-link {% if request.resolver_match.url_name == "noticias" %}active{% endif %}" href="{% url 'core:noticias' %}">Notícias</a></li>
            <li class="nav-item" role="presentation"><a class="nav-link {% if request.resolver_match.url_name == "eventos" %}active{% endif %}" href="{% url 'core:eventos' %}">Eventos</a></li>
            <li class="nav-item" role="presentation"><a class="nav-link {% if request.resolver_match.url_name == "contato" %}active{% endif %}" href="{% url 'core:contato' %}">Contato</a></li>
            <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'core:home' %}#filiados">Filiados</a></li>
            <li class="nav-item" role="presentation"><a class="nav-link {% if request.resolver_match.url_name == "estatuto" %}active{% endif %}" href="{% url 'core:estatuto' %}">Estatuto</a></li>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</div>
{% block content %}
{% endblock %}
<div class="footer-dark">
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-6 align-self-center"><span>© 2019 - Todos os direitos reservados - Federação Tocantinense de Basquete<br></span></div>
        <div class="col-md-6 text-right item text mt-4"><a class="link-RBA" href="https://www.arkanegocios.com.br" target="_blank">Criado por RBA Tech ltda© 2019<br></a><a class="link-restrito" href="/admin">Acesso Restrito</a></div>
      </div>
    </div>
  </footer>
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
<script src="{% static 'js/creative.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.3.1/js/swiper.jquery.min.js"></script>
<script src="{% static 'js/Simple-Slider.js' %}"></script>
<script src="{% static 'js/Swipe-Slider-9.js' %}"></script>
</body>

</html>

ftb/templates/base_old.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}ftb{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}

    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">


    {% endblock %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">ftb</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->


      <!-- place project specific Javascript in this file -->

      <script src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}
  </body>
</html>