config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("ftb.users.urls", namespace="users")),
    path("", include("ftb.core.urls", namespace="core"),),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ftb/core/urls.py
from django.urls import path, include
from django.conf.urls import url

from ftb.core import views

app_name = "core"
urlpatterns = [
    path("", views.home, name="home"),
    path("federacao/", views.federacao, name="federacao"),
    path("noticias/", views.noticias, name="noticias"),
    path("noticias/<int:noticia_id>/", views.noticia_detalhes, name="noticia_detalhes"),
    path("eventos/", views.eventos, name="eventos"),
    path("eventos/<int:evento_id>/", views.evento_detalhes, name="evento_detalhes"),
    path("eventos/<int:evento_id>/inscricao", views.iframe, name="iframe"),
    path("contato/", views.contato, name="contato"),
    path("estatuto/", views.estatuto, name="estatuto"),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

ftb/core/models.py
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver

from model_utils import Choices
from ckeditor.fields import RichTextField


class AbstractModel(models.Model):
    titulo = models.CharField('Título', max_length=100)
    descricao = RichTextField('Descrição', blank=True, null=True)
    criado_em = models.DateTimeField('Criado em', auto_now_add=True)
    atualizado_em = models.DateTimeField('Atualizado em', auto_now=True)

    class Meta:
        abstract = True


class Noticia(AbstractModel):
    imagem = models.ImageField(upload_to='notiticas/imagens', verbose_name='Imagem',
                               null=True, blank=True)
    ordem = models.IntegerField('Ordem', null=True, blank=True)
    destaque = models.BooleanField('Em destaque?', default=False)

    def __str__(self):
        return '{}'.format(self.titulo)

    class Meta:
        verbose_name = 'Notícia'
        verbose_name_plural = 'Notícias'


class Evento(AbstractModel):
    TIPO_EVENTO_COMPETICAO = 10
    TIPO_EVENTO_CURSO = 20

    tipo_evento_choices = Choices(
        (TIPO_EVENTO_COMPETICAO, 'Competição'),
        (TIPO_EVENTO_CURSO, 'Curso')
    )

    tipo_evento = models.IntegerField('Tipo', choices=tipo_evento_choices)
    imagem = models.ImageField(upload_to='eventos/imagens', verbose_name='Imagem',
                               null=True, blank=True)
    data_inicio = models.DateField('Início')
    data_fim = models.DateField('Fim')
    inscricao_data_inicio = models.DateField('Início das inscrições')
    inscricao_data_fim = models.DateField('Fim das inscrições')
    inscricao_formulario = models.CharField('Formulário', max_length=1000)
    # pdf = models.FileField(upload_to='eventos/pdfs', verbose_name='Regulamento/Normas')


@receiver(post_delete, sender=Evento)
@receiver(post_delete, sender=Noticia)
def submission_delete(sender, instance, **kwargs):
    instance.imagem.delete(False)
    # if sender.__name__ == "Evento":
    #     instance.pdf.delete(False)

ftb/core/views.py
from django.shortcuts import render
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail

from .models import Noticia, Evento


def home(request):
    noticias_recentes = Noticia.objects.all().order_by('-criado_em')[:2]
    noticias_destaque = Noticia.objects.filter(destaque=True).order_by('criado_em')[:3]
    template_name = "core/home.html"
    context = {
        'noticias_recentes': noticias_recentes,
        'noticias_destaque': noticias_destaque
    }
    return render(request, template_name, context)


def federacao(request):
    template_name = "core/federacao.html"
    context = {}
    return render(request, template_name, context)


def noticias(request):
    noticias = Noticia.objects.all().order_by('-criado_em')
    template_name = "core/noticias.html"
    context = {
        'noticias': noticias
    }
    return render(request, template_name, context)


def noticia_detalhes(request, noticia_id):
    noticia = Noticia.objects.get(pk=noticia_id)
    template_name = "core/artigo.html"
    context = {
        'artigo': noticia
    }
    return render(request, template_name, context)


def eventos(request):
    cursos = Evento.objects.filter(tipo_evento=Evento.TIPO_EVENTO_CURSO)
    competicoes = Evento.objects.filter(tipo_evento=Evento.TIPO_EVENTO_COMPETICAO)
    template_name = "core/eventos.html"
    context = {
        'cursos': cursos,
        'competicoes': competicoes
    }
    return render(request, template_name, context)


def evento_detalhes(request, evento_id):
    evento = Evento.objects.get(pk=evento_id)
    template_name = "core/artigo.html"
    context = {
        'artigo': evento
    }
    return render(request, template_name, context)


def contato(request):
    data = request.POST
    nome = None
    email = None
    mensagem = None

    if request.method == 'POST':
        nome = data['nome']
        email = data['email']
        mensagem = data['mensagem']

        subject = '[CONTATO-SITE] - Usuário: %s, Email: %s' % (nome, email)
        message = mensagem
        from_email = settings.EMAIL_HOST_USER
        to_list = [settings.EMAIL_HOST_USER]

        send_mail(subject, message, from_email, to_list, fail_silently=True)

        messages.success(request, 'Seu email foi recebido,  em breve entraremos em contato!')

    template_name = "core/contato.html"
    context = {}
    return render(request, template_name, context)


def estatuto(request):
    template_name = "core/estatuto.html"
    context = {}
    return render(request, template_name, context)


def iframe(request, evento_id):
    evento = Evento.objects.get(pk=evento_id)
    template_name = "core/inscricao.html"
    context = {
        'evento': evento
    }
    return render(request, template_name, context)

ftb/core/templates/core/artigo.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="article-clean">
    <div class="container">
      <div class="row">
        <div class="col-lg-10 col-xl-8 offset-lg-1 offset-xl-2">
          {#          <div class="intro">#}
          {#            <h1 class="text-center">{{ artigo.titulo }}</h1>#}
          {#            {% if artigo.imagem %}#}
          {#              <img class="img-fluid" src="{{ artigo.imagem.url }}">#}
          {#            {% endif %}#}
          {#          </div>#}

          <div class="intro">
            <div class="text">
              {{ artigo.descricao|safe }}
            </div>
          </div>

          {#          <div>#}
          {#            {% if artigo.data_inicio %}#}
          {#              Data:#}
          {#              {{ artigo.data_inicio }}#}
          {#            {% endif %}#}
          {#            {% if artigo.data_fim %}#}
          {#              a#}
          {#              {{ artigo.data_fim }}#}
          {#            {% endif %}#}
          {#          </div>#}
          {##}
          {#          <div>#}
          {#            {% if artigo.taxa_inscricao %}#}
          {#              Taxa de inscrição: R$#}
          {#              {{ artigo.taxa_inscricao }}#}
          {#            {% endif %}#}
          {#          </div>#}
          {##}
          {#          <div>#}
          {#            {% if artigo.pdf %}#}
          {#              <a href="{{ artigo.pdf.url }}">Clique aqui para baixar o regulamento</a>#}
          {#            {% endif %}#}
          {#          </div>#}

          {% if artigo.inscricao_formulario %}
            <div class="text-center">
              <a class="btn btn-primary btn-inscricao mb-4" href="{% url 'core:iframe' artigo.pk %}">Formulário de inscrição</a>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

ftb/core/templates/core/contato.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="contact-clean" style="background-image: url({% static 'img/contato-bg.jpg' %}">
    <form method="post" action="{% url 'core:contato' %}">
      {% csrf_token %}
      <h2 class="text-center">Fale Conosco</h2>
      <div class="form-group"><input class="form-control" type="text" name="nome" placeholder="Nome"></div>
      <div class="form-group"><input class="form-control" type="email" name="email" placeholder="Email"></div>
      <div class="form-group"><textarea class="form-control" name="mensagem" placeholder="Mensagem" rows="20"></textarea></div>
      <div class="form-group"><button class="btn btn-primary" type="submit">enviar</button></div>
    </form>
  </div>
{% endblock %}

ftb/core/templates/core/estatuto.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="article-dual-column">
    <div class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1">
          <div class="intro">
            <h1 class="text-center">Estatuto</h1>
            <p class="text-center"> </p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-10 col-lg-3 offset-md-1">
          <div class="toc">
            <p>Sumário</p>
            <ul>
              <li><a href="#">Aliquam In Arcu </a> </li>
              <li><a href="#">Ut vehicula rhoncus</a></li>
              <li><a href="#">Lorem Ipsum </a> </li>
              <li><a href="#">Dolor sit amet</a> </li>
            </ul>
          </div>
        </div>
        <div class="col-md-10 col-lg-7 offset-md-1 offset-lg-0">
          <div class="text">
            <p>Sed lobortis mi. Suspendisse vel placerat ligula. <span style="text-decoration: underline;">Vivamus</span> ac sem lac. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel in
              justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.</p>
            <p>Praesent sed lobortis mi. Suspendisse vel placerat ligula. Vivamus ac lacus. <strong>Ut vehicula rhoncus</strong> elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit <em>pulvinar dict</em> vel in justo. Vestibulum
              ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.</p>
            <h2>Aliquam In Arcu </h2>
            <p>Suspendisse vel placerat ligula. Vivamus ac sem lac. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel in justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices
              posuere cubilia Curae.</p>
            <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae. Suspendisse vel placerat ligula. Vivamus ac sem lac. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit
              pulvinar dictum vel in justo.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

ftb/core/templates/core/eventos.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="noticias-eventos">
    <div class="container">
      <div class="row">
        {% if cursos.count > 0 %}
          <div class="col-md-6 noticia-evento">
            <h2 class="text-center section-heading">Cursos</h2>
            <hr class="my-4">
            {% for curso in cursos %}
              <a href="{% url 'core:evento_detalhes' curso.pk %}">
                <div class="text-center mx-auto service-box mt-5">
                  {% if curso.imagem %}
                    <img class="img-noticia-evento" src="{{ curso.imagem.url }}" width="100%">
                  {% endif %}
                  <h3 class="mb-3">{{ curso.titulo }}</h3>
                  <p class="text-muted mb-0">{{ curso.descricao }}</p>
                </div>
              </a>
            {% endfor %}
          </div>
        {% else %}
          <div class="col-md-6 noticia-evento">
            <h2 class="text-center section-heading">Cursos</h2>
            <hr class="my-4">

            <div class="alert alert-warning text-center" role="alert">
              <span class="text-center section-heading">Não existem cursos registrados</span>
            </div>
          </div>
        {% endif %}

        {% if competicoes.count > 0 %}
          <div class="col-md-6 noticia-evento">
            <h2 class="text-center section-heading">Competições</h2>
            <hr class="my-4">
            {% for competicao in competicoes %}
              <a href="{% url 'core:evento_detalhes' competicao.pk %}">
                <div class="text-center mx-auto service-box mt-5">
                  {% if competicao.imagem %}
                    <img class="img-noticia-evento" src="{{ competicao.imagem.url }}" width="100%">
                  {% endif %}
                  <h3 class="mb-3">{{ competicao.titulo }}</h3>
                  <p class="text-muted mb-0">{{ curso.competicao }}</p>
                </div>
              </a>
            {% endfor %}
          </div>
        {% else %}
          <div class="col-md-6 noticia-evento">
            <h2 class="text-center section-heading">Competições</h2>
            <hr class="my-4">

            <div class="alert alert-warning text-center" role="alert">
              <span class="text-center section-heading">Não existem competições registradas</span>
            </div>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

ftb/core/templates/core/federacao.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="article-clean">
    <div class="container">
      <div class="row">
        <div class="col-lg-10 col-xl-8 offset-lg-1 offset-xl-2">
          <div class="intro">
            <h1 class="text-center">A federação</h1>
            <p class="text-center"> </p><img class="img-fluid" src="{% static 'img/desk.jpg' %}"></div>
          <div class="text">
            <p>Sed lobortis mi. Suspendisse vel placerat ligula. <span style="text-decoration: underline;">Vivamus</span> ac sem lac. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel in
              justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.</p>
            <p>Praesent sed lobortis mi. Suspendisse vel placerat ligula. Vivamus ac lacus. <strong>Ut vehicula rhoncus</strong> elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit <em>pulvinar dict</em> vel in justo. Vestibulum
              ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.</p>
            <h2>Aliquam In Arcu </h2>
            <p>Suspendisse vel placerat ligula. Vivamus ac sem lac. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel in justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices
              posuere cubilia Curae.</p>
            <figure><img class="figure-img" src="{% static 'img/beach.jpg' %}">
              <figcaption>Legenda</figcaption>
            </figure>
            <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae. Suspendisse vel placerat ligula. Vivamus ac sem lac. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit
              pulvinar dictum vel in justo.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

ftb/core/templates/core/form_inscricao.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="article-clean div-google-form">
  {% autoescape off %}{{ evento.inscricao_formulario }}{% endautoescape %}
  </div>
{% endblock %}

ftb/core/templates/core/inscricao.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="article-clean div-google-form">
  {% autoescape off %}{{ evento.inscricao_formulario }}{% endautoescape %}
  </div>
{% endblock %}

ftb/core/templates/core/noticias.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="noticias-eventos">
    <div class="container">
      <h2 class="text-center section-heading">Notícias</h2>
      <hr class="my-4">
      <div class="row">
        {% for noticia in noticias %}
          <div class="col-md-6 noticia-evento">
            <a href="{% url 'core:noticia_detalhes' noticia.pk %}">
              <div class="text-center mx-auto service-box mt-5">
                {% if noticia.imagem %}
                  <img class="img-noticia-evento" src="{{ noticia.imagem.url }}" width="100%">
                {% else %}
                  <img class="img-noticia-evento" src="{% static 'img/contato-bg.jpg' %}" width="100%">
                {% endif %}
                <h3 class="mb-3">{{ noticia.titulo }}</h3>
                <p class="text-muted mb-0">{{ noticia.descricao|truncatechars:100 }}</p>
              </div>
            </a>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}